# Create census db

In [1]:
## Python packages - you may have to pip install sqlalchemy, sqlalchemy_utils, and psycopg2.
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database
import psycopg2
import pandas as pd

In [2]:
dbname = 'census'
username = 'along528'
pswd = 'password'
## 'engine' is a connection to a database
## Here, we're using postgres, but sqlalchemy can connect to other things too.
engine = create_engine('postgresql://%s:%s@localhost/%s'%(username,pswd,dbname))
print engine.url

postgresql://along528:password@localhost/census

In [3]:
## create a database (if it doesn't exist)
if not database_exists(engine.url):
    create_database(engine.url)
print(database_exists(engine.url))

True

# Incarceration, race and income data

In [4]:
path = "/Users/along528/Dropbox/insight/project/datasets/census/incarceration/aff_download/"

csvs = {}
csvs['population_SF1_P1'] = path+'DEC_10_SF1_P1_with_ann.csv'
csvs['population_urban_rural_SF1_P2'] = path+'DEC_10_SF1_P2_with_ann.csv'
csvs['group_quarters_SF1_PCT20'] = path+'DEC_10_SF1_PCT20_with_ann.csv'
csvs['group_quarters_white_SF1_PCT20A'] = path+'DEC_10_SF1_PCT20A_with_ann.csv'
csvs['group_quarters_black_SF1_PCT20B'] = path+'DEC_10_SF1_PCT20B_with_ann.csv'
#csvs[''] = 'DEC_10_SF1_PCT20F_with_ann.csv'
#csvs[''] = 'DEC_10_SF1_PCT20G_with_ann.csv'
#csvs[''] = 'DEC_10_SF1_PCT23_with_ann.csv'
#csvs[''] = 'DEC_10_SF1_QTH1_with_ann.csv'
#csvs[''] = 'DEC_10_SF1_QTP1_with_ann.csv'
csvs['population_race_SF1_QTP3'] = path+'DEC_10_SF1_QTP3_with_ann.csv'
#csvs[''] = 'DEC_10_SF1_QTP5_with_ann.csv'
#csvs[''] = 'DEC_10_SF1_SF1DP1_with_ann.csv'
path = "/Users/along528/Dropbox/insight/project/datasets/census/income/aff_download/"

csvs['total_household_income_ACS_14_5YR_B19001'] = path+'ACS_14_5YR_B19001_with_ann.csv'
csvs['total_household_income_white_ACS_14_5YR_B19001A'] = path+'ACS_14_5YR_B19001A_with_ann.csv'
csvs['total_household_income_black_ACS_14_5YR_B19001B'] = path+'ACS_14_5YR_B19001B_with_ann.csv'

csvs['median_household_income_ACS_14_5YR_B19013'] = path+'ACS_14_5YR_B19013_with_ann.csv'
csvs['median_household_income_white_ACS_14_5YR_B19013A'] = path+'ACS_14_5YR_B19013A_with_ann.csv'
csvs['median_household_income_black_ACS_14_5YR_B19013B'] = path+'ACS_14_5YR_B19013B_with_ann.csv'

dfs = {}
for key in csvs:
    df = pd.read_csv(csvs[key])
    df['GEO.display-label'] = df['GEO.display-label'].map(lambda x: x.replace('ZCTA5 ',''))
    df['GEO.display-label'][0]='zipcode'
    df = df.drop(['GEO.id','GEO.id2'],axis=1)
    names = {}
    for col in df.columns.values:
        names[col] = df[col][0].replace(':','').lower()
    df.rename(columns=names,inplace=True)
    df = df[df.index!=0].reset_index(drop=True)
    df = df.set_index('zipcode')
    df = df.convert_objects(convert_numeric=True)
    df = df.fillna(0)
    dfs[key] = df

/Users/along528/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/along528/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:39: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
/Users/along528/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/along528/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
dfs['population_SF1_P1']

         total
zipcode
00601    18570
00602    41520
00603    54689
00606     6615
00610    29016
00612    67010
00616    11017
00617    24597
00622     7853
00623    43061
00624    26241
00627    35159
00631     1852
00637    25287
00638    18941
00641    31191
00646    38199
00647     6172
00650    14998
00652     4715
00653    13307
00656    21481
00659    41953
00660    17250
00662    43282
00664    16784
00667    25968
00669    29744
00670     9807
00674    44457
...        ...
99786      259
99788       69
99789      402
99790       20
99791      237
99801    29164
99820      479
99824     2111
99825      120
99826      442
99827     2602
99829      777
99830      561
99832      104
99833     3202
99835     8880
99836       52
99840      968
99841      133
99901    13508
99903       31
99918      231
99919      531
99921     1920
99922      384
99923       87
99925      819
99926     1460
99927       94
99929     2338

[33120 rows x 1 columns]

In [6]:
dfs['population_urban_rural_SF1_P2'] = dfs['population_urban_rural_SF1_P2'][['urban','rural']]
dfs['population_urban_rural_SF1_P2']

         urban  rural
zipcode
00601    10679   7891
00602    41520      0
00603    54646     43
00606     2697   3918
00610    25640   3376
00612    62391   4619
00616    10438    579
00617    24161    436
00622     6171   1682
00623    42435    626
00624    22198   4043
00627    30415   4744
00631        0   1852
00637    23163   2124
00638    11839   7102
00641    17647  13544
00646    38199      0
00647     4824   1348
00650    10556   4442
00652     3499   1216
00653    12414    893
00656    18931   2550
00659    37407   4546
00660    17216     34
00662    41045   2237
00664    11300   5484
00667    21332   4636
00669    23005   6739
00670     3214   6593
00674    41451   3006
...        ...    ...
99786        0    259
99788        0     69
99789        0    402
99790        0     20
99791        0    237
99801    22591   6573
99820        0    479
99824     1946    165
99825        0    120
99826        0    442
99827        0   2602
99829        0    777
99830        0    561
99832        0    104
99833        0   3202
99835     7027   1853
99836        0     52
99840        0    968
99841        0    133
99901    10352   3156
99903        0     31
99918        0    231
99919        0    531
99921        0   1920
99922        0    384
99923        0     87
99925        0    819
99926        0   1460
99927        0     94
99929        0   2338

[33120 rows x 2 columns]

In [7]:
names = {}
names[u'institutionalized population (101-106, 201-203, 301, 401-405)'] = u'institutionalized'
names[u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106)'] = u'institutionalized_adult'
names[u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106) - federal detention centers (101)'] = u'institutionalized_adult_federal_detention'
names[u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106) - federal prisons (102)'] = u'institutionalized_adult_federal_prison'
names[u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106) - state prisons (103)'] = u'institutionalized_adult_state_prison'
names[u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106) - local jails and other municipal confinement facilities (104)'] = u'institutionalized_adult_local_jail'
names[u'institutionalized population (101-106, 201-203, 301, 401-405) - juvenile facilities (201-203)'] = u'institutionalized_juvenile'

for key in ['group_quarters_SF1_PCT20',
            'group_quarters_white_SF1_PCT20A',
            'group_quarters_black_SF1_PCT20B']:
    dfs[key].columns
    dfs[key] = dfs[key]\
           [[u'institutionalized population (101-106, 201-203, 301, 401-405)',
           u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106)',
           u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106) - federal detention centers (101)',
           u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106) - federal prisons (102)',
           u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106) - state prisons (103)',
           u'institutionalized population (101-106, 201-203, 301, 401-405) - correctional facilities for adults (101-106) - local jails and other municipal confinement facilities (104)',
           u'institutionalized population (101-106, 201-203, 301, 401-405) - juvenile facilities (201-203)']]
    dfs[key].rename(columns=names,inplace=True)
    dfs[key]

In [8]:
dfs['group_quarters_black_SF1_PCT20B']

,institutionalized,institutionalized_adult,institutionalized_adult_federal_detention,institutionalized_adult_federal_prison,institutionalized_adult_state_prison,institutionalized_adult_local_jail,institutionalized_juvenile
zipcode,,,,,,,
00601,0,0,0,0,0,0,0
00602,0,0,0,0,0,0,0
00603,88,87,0,0,87,0,0
00606,0,0,0,0,0,0,0
00610,4,0,0,0,0,0,0
00612,8,6,0,0,6,0,0
00616,4,0,0,0,0,0,0
00617,3,0,0,0,0,0,0
00622,0,0,0,0,0,0,0
00623,1,0,0,0,0,0,0
00624,2,0,0,0,0,0,0
00627,3,0,0,0,0,0,0
00631,0,0,0,0,0,0,0
00637,0,0,0,0,0,0,0
00638,3,0,0,0,0,0,0
00641,0,0,0,0,0,0,0
00646,11,0,0,0,0,0,0
00647,0,0,0,0,0,0,0
00650,0,0,0,0,0,0,0
00652,0,0,0,0,0,0,0
00653,0,0,0,0,0,0,0
00656,0,0,0,0,0,0,0
00659,2,0,0,0,0,0,0
00660,0,0,0,0,0,0,0
00662,26,0,0,0,0,0,13
00664,11,8,0,0,8,0,0
00667,3,0,0,0,0,0,0
00669,3,0,0,0,0,0,1
00670,3,0,0,0,0,0,0
00674,7,0,0,0,0,0,0
...,...,...,...,...,...,...,...
99786,0,0,0,0,0,0,0
99788,0,0,0,0,0,0,0
99789,0,0,0,0,0,0,0
99790,0,0,0,0,0,0,0
99791,0,0,0,0,0,0,0
99801,10,9,0,0,7,0,1
99820,0,0,0,0,0,0,0
99824,0,0,0,0,0,0,0
99825,0,0,0,0,0,0,0
99826,0,0,0,0,0,0,0
99827,0,0,0,0,0,0,0
99829,0,0,0,0,0,0,0
99830,0,0,0,0,0,0,0
99832,0,0,0,0,0,0,0
99833,0,0,0,0,0,0,0
99835,1,0,0,0,0,0,0
99836,0,0,0,0,0,0,0
99840,0,0,0,0,0,0,0
99841,0,0,0,0,0,0,0
99901,4,0,0,0,0,0,3
99903,0,0,0,0,0,0,0
99918,0,0,0,0,0,0,0
99919,0,0,0,0,0,0,0
99921,0,0,0,0,0,0,0
99922,0,0,0,0,0,0,0
99923,0,0,0,0,0,0,0
99925,0,0,0,0,0,0,0
99926,0,0,0,0,0,0,0
99927,0,0,0,0,0,0,0
99929,0,0,0,0,0,0,0

In [9]:
dfs['population_race_SF1_QTP3'] = dfs['population_race_SF1_QTP3'][[u'number; race - total population - one race - white',
u'number; race - total population - one race - black or african american',
u'number; race - total population - one race - american indian and alaska native',
u'number; race - total population - one race - asian',
u'number; race - total population - one race - native hawaiian and other pacific islander',
u'number; race - total population - one race - some other race',
u'number; race - total population - two or more races']]
names = {}
names[u'number; race - total population - one race - white'] = u'population_white'
names[u'number; race - total population - one race - black or african american'] = u'population_black'
names[u'number; race - total population - one race - american indian and alaska native'] = u'population_native_american'
names[u'number; race - total population - one race - asian'] = u'population_asian'
names[u'number; race - total population - one race - native hawaiian and other pacific islander'] = u'population_nathaw'
names[u'number; race - total population - one race - some other race'] = u'population_other_race'
names[u'number; race - total population - two or more races'] = u'population_mult_race'
dfs['population_race_SF1_QTP3'].rename(columns=names,inplace=True)
dfs['population_race_SF1_QTP3']

,population_white,population_black,population_native_american,population_asian,population_nathaw,population_other_race,population_mult_race
zipcode,,,,,,,
00601,17285,572,65,5,1,402,240
00602,35980,2210,129,22,0,2181,998
00603,45348,4141,140,85,4,3614,1357
00606,5883,314,27,3,8,280,100
00610,23796,2083,100,37,4,2175,821
00612,56488,4130,241,79,6,3964,2102
00616,9339,786,38,4,0,670,180
00617,19831,1885,81,30,0,2159,611
00622,6738,393,13,3,2,483,221
00623,36075,2365,130,35,7,3200,1249
00624,21462,2354,107,42,0,1826,450
00627,30900,1452,112,35,1,1826,833
00631,1724,41,4,0,5,40,38
00637,21566,1387,93,8,2,1587,644
00638,16920,797,22,5,0,810,387
00641,28929,793,68,24,9,934,434
00646,26576,5988,259,90,1,3813,1472
00647,5227,338,37,1,0,400,169
00650,13595,686,42,8,1,405,261
00652,3992,315,20,2,0,253,133
00653,10348,1167,64,6,1,1360,361
00656,17594,1790,94,12,1,1552,438
00659,36608,1855,89,43,0,2483,875
00660,14000,1438,70,16,0,1267,459
00662,35982,3369,146,57,5,2483,1240
00664,15223,576,64,12,1,598,310
00667,20941,1361,63,23,4,3116,460
00669,27078,906,74,22,3,1043,618
00670,8430,515,44,1,1,663,153
00674,36402,3861,222,44,2,2792,1134
...,...,...,...,...,...,...,...
99786,29,1,219,0,0,0,10
99788,10,0,59,0,0,0,0
99789,40,1,350,0,0,0,11
99790,14,0,4,0,0,0,2
99791,16,0,219,0,0,0,2
99801,20286,261,3408,1860,204,355,2790
99820,61,4,352,0,0,2,60
99824,1528,18,284,59,14,31,177
99825,96,0,10,1,0,2,11
99826,404,0,12,5,1,1,19
99827,2093,10,306,15,0,21,157
99829,253,3,408,4,0,1,108
99830,95,1,385,0,1,7,72
99832,66,0,31,0,0,0,7
99833,2569,14,227,98,6,35,253
99835,5797,47,1493,529,30,113,871
99836,47,0,2,2,0,0,1
99840,885,0,34,5,1,4,39
99841,126,1,1,1,0,0,4
99901,9204,79,1912,943,27,93,1250
99903,28,1,0,0,0,0,2
99918,221,0,7,0,0,0,3
99919,467,1,29,4,2,2,26
99921,1382,5,289,11,6,5,222
99922,51,2,290,0,1,4,36
99923,79,0,1,0,1,2,4
99925,350,2,369,4,1,4,89
99926,145,6,1210,2,10,3,84
99927,74,0,10,0,0,0,10
99929,1691,3,384,33,1,5,221

In [10]:
names = {}
names[u'estimate; median household income in the past 12 months (in 2014 inflation-adjusted dollars)'] = 'median_income_estimate'
names[u'margin of error; median household income in the past 12 months (in 2014 inflation-adjusted dollars)'] = 'median_income_error'

for key in ['median_household_income_ACS_14_5YR_B19013',
             'median_household_income_white_ACS_14_5YR_B19013A',
             'median_household_income_black_ACS_14_5YR_B19013B']:
    
    dfs[key].rename(columns=names,inplace=True)

In [11]:
names = {}
names[u'estimate; total'] = 'total_income_estimate'

for key in ['total_household_income_ACS_14_5YR_B19001',
             'total_household_income_white_ACS_14_5YR_B19001A',
             'total_household_income_black_ACS_14_5YR_B19001B']:
    
    dfs[key].rename(columns=names,inplace=True)
    dfs[key] = dfs[key][['total_income_estimate']]

In [12]:
dfs['total_household_income_white_ACS_14_5YR_B19001A']

         total_income_estimate
zipcode
00601                     5612
00602                     7619
00603                    13149
00606                     1686
00610                     6441
00612                    19623
00616                     3375
00617                     7899
00622                     2118
00623                    12295
00624                     6870
00627                    10246
00631                      587
00637                     6029
00638                     5614
00641                     8742
00646                     9337
00647                     1502
00650                     4616
00652                     1252
00653                     3378
00656                     5753
00659                    13416
00660                     2736
00662                     9904
00664                     3921
00667                     7451
00669                     9413
00670                     2839
00674                    13875
...                        ...
99786                       12
99788                        3
99789                        6
99790                        9
99791                        3
99801                     8660
99820                       16
99824                      774
99825                       38
99826                      256
99827                      984
99829                      134
99830                       61
99832                       14
99833                     1093
99835                     2653
99836                        6
99840                      355
99841                       65
99901                     4025
99903                       14
99918                       88
99919                      253
99921                      609
99922                        7
99923                       12
99925                      158
99926                       65
99927                       70
99929                      831

[33120 rows x 1 columns]

In [13]:
joined = pd.concat([dfs['population_SF1_P1'],
                    dfs['population_urban_rural_SF1_P2'],
                    dfs['group_quarters_SF1_PCT20'].rename(columns=lambda x: x+"_all"),
                    dfs['group_quarters_white_SF1_PCT20A'].rename(columns=lambda x: x+"_white"),
                    dfs['group_quarters_black_SF1_PCT20B'].rename(columns=lambda x: x+"_black"),
                    dfs['population_race_SF1_QTP3'],
                    dfs['total_household_income_ACS_14_5YR_B19001'].rename(columns=lambda x: x+"_all"),
                    dfs['total_household_income_white_ACS_14_5YR_B19001A'].rename(columns=lambda x: x+"_white"),
                    dfs['total_household_income_black_ACS_14_5YR_B19001B'].rename(columns=lambda x: x+"_black")
                   ],
                   axis=1)
joined = joined.reset_index()
joined

,zipcode,total,urban,rural,institutionalized_all,institutionalized_adult_all,institutionalized_adult_federal_detention_all,institutionalized_adult_federal_prison_all,institutionalized_adult_state_prison_all,institutionalized_adult_local_jail_all,...,population_white,population_black,population_native_american,population_asian,population_nathaw,population_other_race,population_mult_race,total_income_estimate_all,total_income_estimate_white,total_income_estimate_black
0,00601,18570,10679,7891,57,0,0,0,0,0,...,17285,572,65,5,1,402,240,5820,5612,44
1,00602,41520,41520,0,12,0,0,0,0,0,...,35980,2210,129,22,0,2181,998,13046,7619,314
2,00603,54689,54646,43,826,727,0,0,727,0,...,45348,4141,140,85,4,3614,1357,18020,13149,726
3,00606,6615,2697,3918,0,0,0,0,0,0,...,5883,314,27,3,8,280,100,1898,1686,56
4,00610,29016,25640,3376,62,0,0,0,0,0,...,23796,2083,100,37,4,2175,821,9449,6441,306
5,00612,67010,62391,4619,185,69,0,0,69,0,...,56488,4130,241,79,6,3964,2102,23463,19623,1009
6,00616,11017,10438,579,34,0,0,0,0,0,...,9339,786,38,4,0,670,180,3660,3375,86
7,00617,24597,24161,436,28,0,0,0,0,0,...,19831,1885,81,30,0,2159,611,8308,7899,190
8,00622,7853,6171,1682,46,0,0,0,0,0,...,6738,393,13,3,2,483,221,2361,2118,18
9,00623,43061,42435,626,48,0,0,0,0,0,...,36075,2365,130,35,7,3200,1249,14104,12295,405
10,00624,26241,22198,4043,93,0,0,0,0,0,...,21462,2354,107,42,0,1826,450,8038,6870,210
11,00627,35159,30415,4744,24,0,0,0,0,0,...,30900,1452,112,35,1,1826,833,11543,10246,168
12,00631,1852,0,1852,0,0,0,0,0,0,...,1724,41,4,0,5,40,38,627,587,0
13,00637,25287,23163,2124,88,0,0,0,0,0,...,21566,1387,93,8,2,1587,644,7128,6029,223
14,00638,18941,11839,7102,20,0,0,0,0,0,...,16920,797,22,5,0,810,387,5810,5614,50
15,00641,31191,17647,13544,16,0,0,0,0,0,...,28929,793,68,24,9,934,434,9802,8742,146
16,00646,38199,38199,0,29,0,0,0,0,0,...,26576,5988,259,90,1,3813,1472,12451,9337,1841
17,00647,6172,4824,1348,0,0,0,0,0,0,...,5227,338,37,1,0,400,169,1695,1502,66
18,00650,14998,10556,4442,17,0,0,0,0,0,...,13595,686,42,8,1,405,261,4853,4616,72
19,00652,4715,3499,1216,25,0,0,0,0,0,...,3992,315,20,2,0,253,133,1376,1252,51
20,00653,13307,12414,893,10,0,0,0,0,0,...,10348,1167,64,6,1,1360,361,3876,3378,146
21,00656,21481,18931,2550,48,0,0,0,0,0,...,17594,1790,94,12,1,1552,438,6552,5753,199
22,00659,41953,37407,4546,28,0,0,0,0,0,...,36608,1855,89,43,0,2483,875,13982,13416,143
23,00660,17250,17216,34,142,0,0,0,0,0,...,14000,1438,70,16,0,1267,459,6444,2736,210
24,00662,43282,41045,2237,245,0,0,0,0,0,...,35982,3369,146,57,5,2483,1240,14862,9904,900
25,00664,16784,11300,5484,28,14,0,0,14,0,...,15223,576,64,12,1,598,310,4748,3921,143
26,00667,25968,21332,4636,47,0,0,0,0,0,...,20941,1361,63,23,4,3116,460,8482,7451,220
27,00669,29744,23005,6739,194,0,0,0,0,0,...,27078,906,74,22,3,1043,618,9810,9413,86
28,00670,9807,3214,6593,61,0,0,0,0,0,...,8430,515,44,1,1,663,153,3128,2839,60
29,00674,44457,41451,3006,88,0,0,0,0,0,...,36402,3861,222,44,2,2792,1134,16096,13875,734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33090,99786,259,0,259,0,0,0,0,0,0,...,29,1,219,0,0,0,10,84,12,0
33091,99788,69,0,69,0,0,0,0,0,0,...,10,0,59,0,0,0,0,30,3,0
33092,99789,402,0,402,0,0,0,0,0,0,...,40,1,350,0,0,0,11,100,6,0
33093,99790,20,0,20,0,0,0,0,0,0,...,14,0,4,0,0,0,2,9,9,0
33094,99791,237,0,237,0,0,0,0,0,0,...,16,0,219,0,0,0,2,68,3,0
33095,99801,29164,22591,6573,408,308,0,0,209,0,...,20286,261,3408,1860,204,355,2790,11052,8660,124
33096,99820,479,0,479,0,0,0,0,0,0,...,61,4,352,0,0,2,60,144,16,0
33097,99824,2111,1946,165,0,0,0,0,0,0,...,1528,18,284,59,14,31,177,1029,774,14
33098,99825,120,0,120,0,0,0,0,0,0,...,96,0,10,1,0,2,11,43,38,0
33099,99826,442,0,442,0,0,0,0,0,0,...,404,0,12,5,1,1,19,262,256,0
33100,99827,2602,0,2602,0,0,0,0,0,0,...,2093,10,306,15,0,21,157,1176,984,0
33101,99829,777,0,777,0,0,0,0,0,0,...,253,3,408,4,0,1,108,335,134,0
33102,99830,561,0,561,0,0,0,0,0,0,...,95,1,385,0,1,7,72,218,61,2
33103,99832,104,0,104,0,0,0,0,0,0,...,66,0,31,0,0,0,7,28,14,0
33104,99833,3202,0,3202,0,0,0,0,0,0,...,2569,14,227,98,6,35,253,1367,1093,12
33105,99835,8880,7027,1853,95,3,0,0,0,3,...,5797,47,1493,529,30,113,871,3513,2653,11
33106,99836,52,0,52,0,0,0,0,0,0,...,47,0,2,2,0,0,1,9,6,0
33107,99840,968,0,968,0,0,0,0,0,0,...,885,0,34,5,1,4,39,387,355,0
33108,99841,133,0,133,0,0,0,0,0,0,...,126,1,1,1,0,0,4,65,65,0
33109,99901,13508,10352,3156,120,69,0,0,69,0,...,9204,79,1912,943,27,93,1250,5305,4025,23
33110,99903,31,0,31,0,0,0,0,0,0,...,28,1,0,0,0,0,2,14,14,0
33111,99918,231,0,231,0,0,0,0,0,0,...,221,0,7,0,0,0,3,88,88,0
33112,99919,531,0,531,0,0,0,0,0,0,...,467,1,29,4,2,2,26,277,253,0
33113,99921,1920,0,1920,0,0,0,0,0,0,...,1382,5,289,11,6,5,222,751,609,2
33114,99922,384,0,384,0,0,0,0,0,0,...,51,2,290,0,1,4,36,121,7,0
33115,99923,87,0,87,0,0,0,0,0,0,...,79,0,1,0,1,2,4,12,12,0
33116,99925,819,0,819,0,0,0,0,0,0,...,350,2,369,4,1,4,89,300,158,3
33117,99926,1460,0,1460,0,0,0,0,0,0,...,145,6,1210,2,10,3,84,510,65,5
33118,99927,94,0,94,0,0,0,0,0,0,...,74,0,10,0,0,0,10,91,70,0
33119,99929,2338,0,2338,16,0,0,0,0,0,...,1691,3,384,33,1,5,221,1149,831,3

In [14]:
joined.to_sql('census_by_zipcode',engine,if_exists='replace')